Repository Thesola10/osu-DIVA, pull requests merged in 2021-04, with the labels that each got.

#21 Drop custom hit offsets in favor of osu!mania's defaults
  osu.Game.Rulesets.Diva/Scoring/DivaHitWindows.cs
Labels: enhancement

#17 First implementation for displaying rating
  osu.Game.Rulesets.Diva/Objects/Drawables/DrawableDivaJudgement.cs
  osu.Game.Rulesets.Diva/UI/DivaPlayfield.cs
Labels: backport

#24 Double hit
  .vscode/launch.json
  osu.Game.Rulesets.Diva/Beatmaps/DivaBeatmapConverter.cs
  osu.Game.Rulesets.Diva/DivaRuleset.cs
  osu.Game.Rulesets.Diva/Objects/DoublePressButton.cs
  osu.Game.Rulesets.Diva/Objects/Drawables/DrawableDivaDoubleHitObject.cs
  osu.Game.Rulesets.Diva/Objects/Drawables/DrawableDivaHitObject.cs
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/CircleMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/CircleStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/CrossMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/CrossStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/SquareMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/SquareStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/TriangleMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/TriangleStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/CircleMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/CircleStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/CrossMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/CrossStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/SquareMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/SquareStat.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/TriangleMove.png
  osu.Game.Rulesets.Diva/Resources/Textures/Doubles/XB/TriangleStat.png
  osu.Game.Rulesets.Diva/UI/DrawableDivaRuleset.cs
Labels: enhancement

#27 key mod
  osu.Game.Rulesets.Diva/Beatmaps/DivaBeatmapConverter.cs
  osu.Game.Rulesets.Diva/DivaRuleset.cs
  osu.Game.Rulesets.Diva/Mods/DivaKeyMod.cs
  osu.Game.Rulesets.Diva/Mods/DivaModKey1.cs
  osu.Game.Rulesets.Diva/Mods/DivaModKey2.cs
  osu.Game.Rulesets.Diva/Mods/DivaModKey3.cs
  osu.Game.Rulesets.Diva/Mods/DivaModKey4.cs
Labels: backport, enhancement

#30 no doubles mod
  osu.Game.Rulesets.Diva/Beatmaps/DivaBeatmapConverter.cs
  osu.Game.Rulesets.Diva/DivaRuleset.cs
  osu.Game.Rulesets.Diva/Mods/DivaKeyMod.cs
  osu.Game.Rulesets.Diva/Mods/DivaModNoDoubles.cs
Labels: enhancement
